# .goreleaser.yml
version: 2

# Opcional: defina o nome do projeto se necessário
project_name: cloud-service-pack

release:
  # Opcional: você pode remover a seção 'github' se o repositório 
  # no qual você está executando a action for o 'raywall/cloud-service-pack'.
  # GoReleaser infere isso automaticamente.
  name_template: "Release {{ .Tag }}"
  github:
    owner: raywall
    name: cloud-service-pack

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'Merge pull request'
    - 'Merge branch'
