# Arquivo de Políticas

ValidarIdade:
- $.idade >= 18
- $.tipo == "adulto"

ValidarValorTransacao:
- $.valor > 0
- $.valor <= $.limiteMaximo
- $.moeda == "BRL" OR $.moeda == "USD"

CalcularDesconto:
- $.valor > 100
- SET $.desconto = EXP($.valor * 0.1)
- IF $.cliente.tipo == "premium" THEN SET $.desconto = EXP($.valor * 0.15)

AplicarImpostos:
- SET $.impostos.iss = EXP($.valor * 0.05)
- IF $.tipo == "servico" THEN SET $.impostos.pis = EXP($.valor * 0.0165)

ValidarEndereco:
- $.endereco.cep != null
- $.endereco.cidade != null
- $.endereco.estado IN ["SP", "RJ", "MG", "RS"]

VerificarLimites:
- COUNT($.transacoes) < $.limites.maxTransacoes
- SET $.somaTransacoes = SUM($.transacoes[*].valor)
- EXP($.somaTransacoes + $.valor) <= $.limites.valorTotal

VerificaArray:
- ADD [{"nome":"teste","valor":1234}] TO $.endereco.estado
